# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
  - commit-msg

default_stages:
  - pre-commit

fail_fast: true

repos:
  # Default pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-symlinks
      - id: debug-statements
      - id: no-commit-to-branch
        args: [--branch, main]

  # Commitlint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"

  # Codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  # Local pre-commit-hooks
  - repo: local
    hooks:
      - id: prettier
        stages:
          - pre-commit
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        types:
          - text
        args: []
        require_serial: false
        additional_dependencies:
          - "prettier@3.3.3"
        minimum_pre_commit_version: "0"
      - id: sign-off-commit
        stages:
          - prepare-commit-msg
        name: sign-off-commit
        entry: scripts/pre-commit/sign-off-commit.sh
        language: system
